apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: gamma
spec:
  limits:
  - default:
      cpu: 1
      memory: 500m
    defaultRequest:
      cpu: 0.5
      memory: 100m
    type: Container
