apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxx
  labels:
    app: app 
    name: nginx-name
spec:
  selector:
    matchLabels:
      app: nginx-app
      name: nginx-name
  template:
    metadata:
      labels:
        app: nginx-app
        name: nginx-name
    spec:
      containers:
      - image: httpd:nginx
        name: nginx-container
        ports:
        - name: http
          containerPort: 8030