apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  name: nginx-pvc
spec:
  # Notice the storage-class name matches the storage class in the PV we made in the previous step.
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi