apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alone-pod
  name: alone-pod
  namespace: alone
spec:
  containers:
  - image: nginx:1.16.1-alpine
    name: alone
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}