apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-server
  name: web-server
  namespace: alone
spec:
  containers:
  - image: nginx:1.16.1-alpine
    name: nginx
  - image: httpd:2.4.41-alpine
    name: httpd
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}